apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-stats-config
  namespace: minecraft-stats
  labels:
    app: minecraft-stats
data:
  MINECRAFT_STATS_PATH: "/minecraft-data/server_chavalda/stats"
  MINECRAFT_USER_CACHE_PATH: "/minecraft-data/usercache.json"
  MINECRAFT_SERVER_NAME: "Server De la Chavalada"
