apiVersion: v1
kind: Service
metadata:
  name: minecraft-stats
  namespace: minecraft-stats
  labels:
    app: minecraft-stats
spec:
  type: ClusterIP
  selector:
    app: minecraft-stats
  ports:
  - name: http
    port: 80
    targetPort: 8080
