apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-stats-ingress
  namespace: minecraft-stats
  labels:
    app: minecraft-stats
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - minecraft-stats.apptolast.com
    secretName: minecraft-stats-tls
  rules:
  - host: minecraft-stats.apptolast.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft-stats
            port:
              number: 80
